Repository HttpRafa/atomic-cloud, pull requests merged in 2025-02, with the labels that each got.

#61 feat: Improved docs
  docs/api/index.md
  docs/api/jvm/channels.md
  docs/api/jvm/index.md
  docs/api/options/jvm.md
  docs/cli/index.md
  docs/controller/drivers/index.md
  docs/controller/drivers/wasm/index.md
  docs/controller/drivers/wasm/local/index.md
  docs/controller/drivers/wasm/permissions.md
  docs/controller/drivers/wasm/pterodactyl/index.md
  docs/controller/index.md
  docs/controller/installation/normal.md
  docs/controller/usage/retrieve_token.md
  docs/features/api.md
  docs/features/backend.md
  docs/features/cli.md
  docs/features/no_proxy.md
  docs/index.md
  docs/installation/docker.md
  docs/installation/normal.md
  docs/usage/cli/index.md
  docs/usage/controller/index.md
  docs/usage/controller/plugins/index.md
  docs/usage/controller/plugins/wasm/index.md
  docs/usage/controller/plugins/wasm/local/index.md
  docs/usage/controller/plugins/wasm/permissions.md
  docs/usage/controller/plugins/wasm/pterodactyl/index.md
  docs/usage/controller/templates/index.md
  docs/usage/images/first_startup.png
  docs/usage/retrieve_token.md
  docs/wrapper/index.md
Labels: 📖 documentation, 🟧 medium

#59 feat: Implement way to see the logs of a server from the CLI
  cli/Cargo.toml
  cli/src/application/menu/connection.rs
  cli/src/application/menu/connection/screen.rs
  cli/src/application/menu/connection/screen/start.rs
  cli/src/application/menu/connection/start.rs
  cli/src/application/network.rs
Labels: 🫙 feature, 🟧 medium

#74 fix: Server are stopped twice
  controller/src/application.rs
  controller/src/application/group.rs
  controller/src/application/group/manager.rs
  controller/src/application/node.rs
  controller/src/application/plugin.rs
  controller/src/application/plugin/runtime/wasm.rs
  controller/src/application/plugin/runtime/wasm/ext.rs
  controller/src/application/plugin/runtime/wasm/ext/guard.rs
  controller/src/application/plugin/runtime/wasm/ext/screen.rs
  controller/src/application/plugin/runtime/wasm/init.rs
  controller/src/application/plugin/runtime/wasm/node.rs
  controller/src/application/server.rs
  controller/src/application/server/guard.rs
  controller/src/application/server/manager.rs
  controller/src/application/server/manager/action.rs
  controller/src/application/server/manager/restart.rs
  controller/src/application/server/manager/start.rs
  controller/src/application/server/manager/stop.rs
  controller/src/application/server/screen/manager.rs
  controller/src/main.rs
  plugins/local/src/main.rs
  plugins/local/src/node.rs
  plugins/local/src/node/screen.rs
  plugins/local/src/node/server.rs
  plugins/local/src/node/server/manager.rs
  plugins/local/src/plugin.rs
  protocol/wit/plugin.wit
Labels: 🐛 bug, 🟧 medium

#79 feat: Add port mappings to local plugin
  common/src/allocator.rs
  plugins/local/configs/config.toml
  plugins/local/src/node.rs
  plugins/local/src/plugin.rs
  plugins/local/src/plugin/config.rs
Labels: 🫙 feature, 🟩 simple

#80 feat: Implement self signed certificates
  cli/Cargo.toml
  cli/src/application/menu.rs
  cli/src/application/menu/create_profile.rs
  cli/src/application/network.rs
  cli/src/application/profile.rs
  clients/jvm/common/src/main/java/io/atomic/cloud/common/connection/CloudConnection.java
  clients/jvm/paper/src/main/java/io/atomic/cloud/paper/CloudPlugin.java
  clients/wrapper/Cargo.toml
  common/Cargo.toml
  controller/Cargo.toml
  controller/configs/config.toml
  controller/src/application.rs
  controller/src/application/global.rs
  controller/src/application/plugin/manager.rs
  controller/src/application/plugin/runtime/wasm.rs
  controller/src/application/plugin/runtime/wasm/ext.rs
  controller/src/application/plugin/runtime/wasm/ext/tls.rs
  controller/src/application/plugin/runtime/wasm/init.rs
  controller/src/config.rs
  controller/src/network.rs
  controller/src/network/tls.rs
  controller/src/storage.rs
  plugins/local/Cargo.toml
  plugins/local/src/node/server.rs
  protocol/wit/plugin.wit
Labels: 🫙 feature, 🟥 hard
