Repository HttpRafa/atomic-cloud, pull requests merged in 2025-03, with the labels that each got.

#81 feat: Cleanup and support latest controller
  .github/workflows/release.yml
  Cargo.toml
  clients/wrapper/Cargo.toml
  clients/wrapper/build.rs
  clients/wrapper/src/application.rs
  clients/wrapper/src/application/detection.rs
  clients/wrapper/src/application/heart.rs
  clients/wrapper/src/application/network.rs
  clients/wrapper/src/application/process.rs
  clients/wrapper/src/application/process/stdin.rs
  clients/wrapper/src/application/process/stdout.rs
  clients/wrapper/src/application/transfer.rs
  clients/wrapper/src/application/user.rs
  clients/wrapper/src/main.rs
  controller/Cargo.toml
  controller/src/network.rs
  eggs/egg-paper.json
  plugins/local/src/node/server.rs
  rust-toolchain.toml
  templates/papermc/prepare/unix.sh
  templates/papermc/prepare/windows.ps1
  templates/papermc/startup/unix.sh
  templates/papermc/startup/windows.ps1
  templates/papermc/template.toml
  templates/vanilla/prepare/unix.sh
  templates/vanilla/prepare/windows.ps1
  templates/vanilla/startup/unix.sh
  templates/vanilla/startup/windows.ps1
  templates/vanilla/template.toml
Labels: 🫙 feature, 🟩 simple

#90 fix: Fix some bugs
  controller/configs/config.toml
  controller/src/application/plugin/runtime/wasm.rs
  controller/src/application/plugin/runtime/wasm/ext/screen.rs
  controller/src/application/plugin/runtime/wasm/node.rs
  controller/src/application/server/screen/manager.rs
  plugins/local/configs/config.toml
  plugins/pelican/configs/config.toml
  plugins/pelican/src/main.rs
  plugins/pelican/src/node/backend/common.rs
  plugins/pelican/src/node/backend/server/data.rs
  plugins/pelican/src/node/screen.rs
  plugins/pelican/src/node/server.rs
  plugins/pelican/src/node/server/manager.rs
Labels: 🐛 bug, 🟩 simple

#95 feat: Add max memory feature to local plugin
  plugins/local/src/node/server.rs
  plugins/pelican/src/node/server.rs
  templates/papermc/startup/unix.sh
  templates/papermc/startup/windows.ps1
  templates/vanilla/startup/unix.sh
  templates/vanilla/startup/windows.ps1
Labels: 🫙 feature, 🟩 simple

#96 feat: Improve design of chat messages
  clients/jvm/build.gradle.kts
  clients/jvm/paper/src/main/java/io/atomic/cloud/paper/command/CloudCommand.java
  clients/jvm/paper/src/main/java/io/atomic/cloud/paper/command/DisposeCommand.java
  clients/jvm/paper/src/main/java/io/atomic/cloud/paper/command/SendCommand.java
  clients/jvm/paper/src/main/java/io/atomic/cloud/paper/enums/MessageEnum.java
Labels: 🫙 feature, 🟧 medium
